services:
  nginx:
    image: nginx:latest
    container_name: lar_nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3030:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/app
    depends_on:
      - php-fpm
    networks:
      - app-network
  
  php-fpm:
    user: "${UID:-1000}:${GID:-1000}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: docker/php.dev.Dockerfile
    container_name: lar_php
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - DB_ROOT_PASS=qwerty123
      - DB_NAME=test
      - DB_USER=test
      - DB_USER_PASS=qwerty123
    networks:
      - app-network
  
  mysql:
    image: mysql:5.7
    container_name: lar_mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty123
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=qwerty123
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro
    networks:
      - app-network

volumes:
  mysql-data:
    driver: local
  node_modules:
    driver: local

networks:
  app-network:
    driver: bridge